services:
  mysql:
    image: mysql:8.0.36-debian
    container_name: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=identity_service
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  identity_service:
    container_name: identity_service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DBMS_CONNECTION: jdbc:mysql://mysql:3306/identity_service
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      LOGSTASH_HOST: logstash:5600
    networks:
      - default

  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - default

  kibana:
    image: kibana:7.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - default

  logstash:
    image: logstash:7.14.1
    container_name: logstash
    ports:
      - "5600:5600"
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - default

networks:
  default:
    name: identity_service

volumes:
  mysql_data: